# -*- coding: utf-8 -*-
"""Miniproject_studentprogresstracker_Manoj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DatcbbBBEm5HVwqKJt9EArYFlsGnZPCU
"""

print("--------------------------------------------")
print("******STUDENT PROGRESS TRACKING SYSTEM******")
print("--------------------------------------------")
NAME=input("STUDENT NAME:-")          #Enter student name
CLASS=input("STUDENT CLASS:-")        #Enter student class
ROLL=input("STUDENT ROLL NO:-")       #Enter roll no
print("--------------------------------------------")
SUBJECT=int(input("Enter your subjects:-"))     #Enter your  subjects
n=SUBJECT
marks=[]      #Marks in array
for i in range(0,n):
    mark = int(input(f"enter subject{i+1} your marks:- "))        #Marks is assign to the each subject
    marks.append(mark)
    if mark <= 34:
        print(f"You have failed in subject {i+1}")       #here if any subject is less than 34 it return failed
print(f"marks:-{marks}")
print("--------------------------------------------")
Total=0
for i in range(0,n):
    Total=marks[i]+Total    #Print Total marks by given marks
print(f"Total:-{Total}")
Average=0
Average=Total/n
print(f"Average:-{Average}")    #Print Average of Total marks
print("--------------------------------------------")
#print GRADE by on the Average
if Average>=90 and Average<=100:
    Grade="A"
elif Average>=75 and Average<=89:
    Grade="B"
elif Average>=50 and Average<=75:
    Grade="C"
elif Average>=35 and Average<=49:
    Grade="D"
elif Average<=34:
    print(f"you are Failed{Average}")
else:
    print("you are pass")

print(f"Grade:-{Grade}")

if any(mark <= 34 for mark in marks):
    status = "FAIL"
else:
    status = "PASS"
print(f"Result: {status}")
print("--------------------------------------------")
print("******STUDENT PROGRESS REPORT******")        #Print the student progress report
print("\n")
print(NAME)
print(CLASS)
print(ROLL)
print(Total)
print(Average)
print(Grade)
print("--------------------------------------------")
print("******MENU******")
print("--------------------------------------------")
print("what do you want to do next ")
print("--------------------------------------------")
Choice=input("enter your Choice:-")
while Choice!="3":
    if Choice=="1":
        print(f"marks:-{marks}")
        Choice=input("enter your Choice:-")
        print("--------------------------------------------")
    elif Choice=="2":
        print("--------------------------------------------")
        print("\n******STUDENT PROGRESS REPORT******")
        print(NAME)
        print(CLASS)
        print(ROLL)
        print(f"marks:-{marks}")
        print(f"Total:-{Total}")
        print(f"Average:-{Average}")
        print(f"Grade:-{Grade}")
        print(f"Result: {status}")
        Choice=input("enter your Choice:-")
        #break
        print("--------------------------------------------")
    elif Choice=="3":
        exit
print("*****THANK YOU******")